#ifndef _EFI_INSTALL_PROTOCOL_INTERFACE_H_
#define _EFI_INSTALL_PROTOCOL_INTERFACE_H_

#include "efi_types.h"

typedef EFI_STATUS(EFI_API *EFI_INSTALL_PROTOCOL_INTERFACE)(
    IN OUT EFI_HANDLE *Handle,
    IN EFI_GUID *Protocol,
    IN EFI_INTERFACE_TYPE InterfaceType,
    IN VOID *Interface);

#endif /* _EFI_INSTALL_PROTOCOL_INTERFACE_H_ */
