#ifndef _EFI_UNINSTALL_PROTOCOL_INTERFACE_H_
#define _EFI_UNINSTALL_PROTOCOL_INTERFACE_H_

#include "efi_types.h"

typedef EFI_STATUS(EFI_API *EFI_UNINSTALL_PROTOCOL_INTERFACE)(
    IN EFI_HANDLE Handle,
    IN EFI_GUID *Protocol,
    IN VOID *Interface);

#endif /* _EFI_UNINSTALL_PROTOCOL_INTERFACE_H_ */
