#ifndef _EFI_OPEN_PROTOCOL_INFORMATION_H_
#define _EFI_OPEN_PROTOCOL_INFORMATION_H_

#include "efi_types.h"

typedef EFI_STATUS(EFI_API *EFI_OPEN_PROTOCOL_INFORMATION)(
    IN EFI_HANDLE Handle,
    IN EFI_GUID *Protocol,
    OUT EFI_OPEN_PROTOCOL_INFORMATION_ENTRY **EntryBuffer,
    OUT UINTN *EntryCount);

#endif /* _EFI_OPEN_PROTOCOL_INFORMATION_H_ */
