#ifndef _EFI_GET_NEXT_HIGH_MONOTONIC_COUNT_H_
#define _EFI_GET_NEXT_HIGH_MONOTONIC_COUNT_H_

#include "efi_types.h"

typedef EFI_STATUS(EFI_API *EFI_GET_NEXT_HIGH_MONOTONIC_COUNT)(
    OUT UINT32 *HighCount);

#endif /* _EFI_GET_NEXT_HIGH_MONOTONIC_COUNT_H_ */
